<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@page import="ryerson.ca.helper.Appointment,ryerson.ca.helper.AppointmentsXML"%>
<%! private String escape(Object value) { return value == null ? "" : value.toString().replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;"); } %>
<% AppointmentsXML data = (AppointmentsXML) request.getAttribute("appointmentResults");
boolean searched = "search".equals(request.getParameter("pageName"));
int count = data == null || data.getAppointments() == null ? 0 : data.getAppointments().size(); %>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Appointments — Find your next appointment</title><link rel="stylesheet" href="assets/app.css"></head><body><a class="skip" href="#main">Skip to content</a><div class="shell"><header><a class="brand" href="./"><span class="mark" aria-hidden="true">＋</span>Appointments<span class="tag"> / BOOKING</span></a><nav class="nav" aria-label="Main"><a href="./">Find a service</a><span class="pill">Course demo</span></nav></header><main id="main"><section class="hero"><p class="eyebrow">Make room for yourself</p><h1>Your next appointment.<br><em>A little less effort.</em></h1><p class="lede">Find a service, check its booking status, and take the next step. All in one place.</p></section><div class="layout"><div><section class="panel search-panel" aria-labelledby="search-heading"><div class="section-top"><h2 id="search-heading">Find an appointment</h2><span class="number">01 / DISCOVER</span></div><form class="search-form" action="FrontEnd" method="post"><input type="hidden" name="pageName" value="search"><div class="field"><label for="query">Service name</label><input id="query" name="query" type="search" placeholder="What are you looking for?" value="<%=escape(request.getParameter("query"))%>" required></div><button type="submit">Search <span aria-hidden="true">↗</span></button></form><p class="hint">Try <a href="FrontEnd?pageName=search&amp;query=Psychology">Psychology</a> to explore the demo.</p></section><section aria-labelledby="results-heading"><div class="section-top"><h2 id="results-heading">Search results</h2><span class="number"><%=count%> result<%=count == 1 ? "" : "s"%></span></div>
<% if (count > 0) { for (Appointment appointment : data.getAppointments()) { %>
<article class="result"><div class="result-left"><span class="service-icon" aria-hidden="true">✳</span><div><p class="meta">APPOINTMENT · <%=escape(appointment.getId())%></p><h3><%=escape(appointment.getServiceName())%></h3><p class="meta">Sign in to check availability</p></div></div>
<a class="button" href="#sign-in">Sign in to book</a></article>
<% } } else { %><div class="empty"><h3><%= searched ? "No appointments found." : "What would you like to book?" %></h3><p><%= searched ? "Try a different service name, or search for Psychology to explore the demo." : "Search for a service above to see your appointment options." %></p></div><% } %></section></div><aside class="side" id="sign-in"><section class="panel"><p class="eyebrow">Your account</p><h2>Welcome back.</h2><p>Sign in to book an appointment from your search results.</p><form class="login-form" action="FrontEnd" method="post"><input type="hidden" name="pageName" value="login"><div class="field"><label for="username">Username</label><input id="username" name="username" autocomplete="username" required></div><div class="field"><label for="password">Password</label><input id="password" type="password" name="password" autocomplete="current-password" required></div><button type="submit">Sign in <span aria-hidden="true">→</span></button></form><div class="demo">Exploring the demo?<br>Username: <code>AndrewBadie</code><br>Password: <code>1234</code></div></section><div class="note"><h3>Start with a search.</h3><p>You can browse services without signing in. Sign in when you’re ready to book.</p></div></aside></div></main><footer class="footer"><span>Appointments · COE692</span><span>A student-built appointment booking demo.</span></footer></div></body></html>